# Generated by Django 5.1 on 2024-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.URLField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
    ]
